name: 'SpotiCraft'
version: '${version}'
main: 'io.github.kuroka3.spoticraft.SpotiCraftPlugin'
api-version: '1.21'

commands:
  spoticraft:
    description: Default command for SpotiCraft plugin
    usage: /spoticraft (reload)

  gettoken:
    usage: /
  refreshtoken:
    usage: /
  skip:
    usage: /
  pause:
    usage: /
  getstate:
    usage: /
  monitoring:
    usage: /