name: 'SpotiCraft'
version: '${version}'
main: 'io.github.kuroka3.spoticraft.SpotiCraftPlugin'
api-version: '1.20'

commands:
  gettoken:
    usage: /
  refreshtoken:
    usage: /
  skip:
    usage: /
  pause:
    usage: /
  getstate:
    usage: /
  monitoring:
    usage: /