name: 'SpotiCraft'
version: '${version}'
main: 'io.github.kuroka3.spoticraft.SpotiCraftPlugin'
api-version: '1.21'

commands:
  spoticraft:
    description: Default command for SpotiCraft plugin
    usage: /spoticraft (reload)
  spotify:
    description: Manage Spotify
    usage: /spotify [start/pause/next/prev/set_repeat/set_volume/toggle_shuffle/seek_to_position] (value)

  gettoken:
    usage: /
  refreshtoken:
    usage: /
  getstate:
    usage: /